[package]
name = "winkeyhive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nt-hive = "0.2"
zerocopy = "0.5"
crc = "2.1"
hex_fmt = "0.3"